### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by zhuzhu129130** [rookiepig/CrossScaleStereo#2]
hi，while run the program，I found memory leak in the program，but I dont know where the bug？

**Comment by rookiepig** [comment]
Hi I am too busy to maintain this project. 

Besides, please be specific when ask for help. 

You did not provide any detail information like the image size, the command args. Others can not help you in this situation.

**Comment by zyfsa** [comment]
师兄，您好。我想我懂他的得意思，也遇到同样的问题，就是在
"CEN" "GF" "WM" "1" "F:\kitti2012\training2012\colored_0\000000_10.png" "F:\kitti2012\training2012\colored_1\000000_10.png" "F:\\ld.png" "F:\\rd.png"  "256" "1"    
配置的时候，出现insufficient memory《failed to allocate 3628964 byutes》的错误,当在middlebury上时没有问题，请问之前您遇到了吗？我试过换到服务器上跑也有问题，请问方便回复一下吗？我是研一的学生在学习这个，方便的话可以加微信吗？请问

**Comment by zyfsa** [comment]
师兄，我怀疑是图片大小的问题，我调试了很久都没有成功，另外我刚进入，有很多问题，真诚的希望能像您请教，谢谢了

**Comment by zhuzhu129130** [comment]
你好，最近调试了下，发现costVol这个变量，结束之后，没有释放，只释放smPyr这个双重指针，不太确定能不能释放干净。我是因为要循环调用，所以看出内存泄漏，希望有时间给予指点

**Comment by zyfsa** [comment]
您好，我的微信，qq都是347219809，可以添加，然后相互交流。我是在代价聚合那一步就insufficient memory,这个时候costvol暂时也不能释放吧，我而且在内存更大服务器跑了，还是一样有问题，后面怀疑会不会是vs2015本身要求只能用多大的栈

**Comment by zyfsa** [comment]
我是跑一张图片就有问题

**Comment by sunshinnnn** [comment]
> 你好，最近调试了下，发现costVol这个变量，结束之后，没有释放，只释放smPyr这个双重指针，不太确定能不能释放干净。我是因为要循环调用，所以看出内存泄漏，希望有时间给予指点

我也调试了，确实是这个问题。我改进了一下。没去管外面那层数组，delete删里面的元素，就好了。

**Comment by rookiepig** [comment]
嗨，抱歉，工作繁忙很久没有看个人邮箱了。 @sunshinnnn 非常感谢你的指正，pull request有一个小问题，改正了我去通过下~

**Comment by rookiepig** [comment]
> 师兄，您好。我想我懂他的得意思，也遇到同样的问题，就是在
> "CEN" "GF" "WM" "1" "F:\kitti2012\training2012\colored_0\000000_10.png" "F:\kitti2012\training2012\colored_1\000000_10.png" "F:\ld.png" "F:\rd.png" "256" "1"
> 配置的时候，出现insufficient memory《failed to allocate 3628964 byutes》的错误,当在middlebury上时没有问题，请问之前您遇到了吗？我试过换到服务器上跑也有问题，请问方便回复一下吗？我是研一的学生在学习这个，方便的话可以加微信吗？请问

看你这个报错，应该还是内存不够的问题，跑KITTI数据时务必小心，由于图片和disparity range都非常大，很容易爆内存。

**Comment by sunshinnnn** [comment]
> 嗨，抱歉，工作繁忙很久没有看个人邮箱了。 @sunshinnnn 非常感谢你的指正，pull request有一个小问题，改正了我去通过下~

很抱歉过了4天才改正pull request。上一次看到你的这条回复的时候我看错了意思，以为你要亲自去改，就没有的处理了。

**Comment by rookiepig** [comment]
> > 嗨，抱歉，工作繁忙很久没有看个人邮箱了。 @sunshinnnn 非常感谢你的指正，pull request有一个小问题，改正了我去通过下~
> 
> 很抱歉过了4天才改正pull request。上一次看到你的这条回复的时候我看错了意思，以为你要亲自去改，就没有的处理了。

Thanks~ Done :)
