### ISSUE TITLE
the error rate?

### ISSUE THREAD

**Issue by zyfsa** [rookiepig/CrossScaleStereo#3]
why I test on the kitti training set,my error is lower than your result ,futhermore,the difference is  very big,because the dataset have been updated?thank you ,very much

**Comment by rookiepig** [comment]
Please specify your parameters, acc results and dataset. I cannot answer your question without this info...

**Comment by zyfsa** [comment]
因为我知道大家都会中文，就偷懒了。谢谢回答，您好，我使用的配置是cen,box,sg,lambda=1，5个尺度(我实验发现，目前使用box比gf 好，使用lambda=1.2要好)，目前使用测出来box 的是7.4，gf是7.1(单尺度box是10.5，gf是8.7，比您之前测出来的要好，我用的是devkit上的matlab代码(会是评测代码错了吗)，测的是noc,occ)，另外我想问一下可能是因为kitti2012发生了一次更新吗？另外我想请问是您使用在训练集和放在网上的评测结果使用的配置是什么啊？是否使用NL后处理在kitti 上效果很差?请您回复一下，

**Comment by zyfsa** [comment]
hi,can you again test your result in the kitti 2012 dataset?please,and told me,let me have a baseline.thank you

**Comment by rookiepig** [comment]
> 因为我知道大家都会中文，就偷懒了。谢谢回答，您好，我使用的配置是cen,box,sg,lambda=1，5个尺度(我实验发现，目前使用box比gf 好，使用lambda=1.2要好)，目前使用测出来box 的是7.4，gf是7.1(单尺度box是10.5，gf是8.7，比您之前测出来的要好，我用的是devkit上的matlab代码(会是评测代码错了吗)，测的是noc,occ)，另外我想问一下可能是因为kitti2012发生了一次更新吗？另外我想请问是您使用在训练集和放在网上的评测结果使用的配置是什么啊？是否使用NL后处理在kitti 上效果很差?请您回复一下，

抱歉，工作繁忙， 没有时间来回复，应该是因为KITTI 2012发生了更新
