### ISSUE TITLE
为什么无法读取我键入的参数？

### ISSUE THREAD

**Issue by rintiunse** [rookiepig/CrossScaleStereo#4]
每当我键入参数后就自动结束程序，是键入的格式不对吗？

**Comment by rookiepig** [comment]
你这种描述问题的方式，别人没办法回答你。

**Comment by rintiunse** [comment]
我重新描述下问题，困扰我一天了。代码中的Usage: [CC_METHOD] [CA_METHOD] [PP_METHOD] [C_ALPHA] [lImg] [rImg] [lDis] [rDis] [maxDis] [disSc]这些参数是怎么输入的？是直接在这里赋值吗？string ccName = argv[ 1 ]="CEN";代码可以运行但是在出现命令窗口后，我按任意键继续运行，出现“请按任意键继续”就退出了命令窗口，什么结果也没有生成。

**Comment by rintiunse** [comment]
@rookiepig 不知道是哪里理解的有问题

**Comment by rintiunse** [comment]
明白明白了，大家自行百度下main(argc, argv)的用法。

**Comment by rookiepig** [comment]
恩， 很高兴你自己独立解决了 :)
