### ISSUE TITLE
not declare m_mst_value_sum_aggregated_from_parent_to_child

### ISSUE THREAD

**Issue by JDYG** [rookiepig/CrossScaleStereo#8]
It seems that ‘m_mst_value_sum_aggregated_from_parent_to_child’ was not declared in qx_tree_filter.cpp

I searched the whole project and didn't find the declaration of m_mst_value_sum_aggregated_from_parent_to_child

**Comment by rookiepig** [comment]
Indeed, this code from QingXiong Yang's non-local code base. This filtering code is not useful for cost aggregtation.
